---
vars_prompt:
  - name: "mas_password"
    prompt: "Enter your Mac App Store password"
    private: yes  # Ensures the input is hidden (like typing a password in the terminal)

tasks:
  - name: Login to MAS
    command: "mas signin {{ mas_email }} '{{ mas_password | quote }}'"
    no_log: true

  - name: Check if application exists
    stat:
      path: "/Applications/{{ item }}"
    register: app
    loop:
      - 'GarageBand.app'
      - 'Numbers.app'
      - 'Keynote.app'
      - 'Pages.app'

  - name: Remove application
    command: sudo rm -rf "/Applications/{{ item }}"
    become: yes
    become_method: sudo
    when: item in app.results | selectattr('stat.exists') | map(attribute='item')
    loop:
      - 'GarageBand.app'
      - 'Numbers.app'
      - 'Keynote.app'
      - 'Pages.app'
    
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - 'Finder'
  - 'Mail'
  - 'Messages'
  - 'Reminders'
  - 'Notes'
  - 'Safari'
  - 'iTunes'
  - 'Music'
  - 'TV'
  - 'Podcasts'
  - 'Launchpad'
  - 'App Store'
  - 'News'
  - 'Stocks'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: true
# sudoers_custom_config: ''
sudoers_custom_config: |
  # Allow users in admin group to use sudo with no password.
  %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc  # Z shell configuration file, used to customize the shell environment; typically located at ~/.zshrc
  - .gitignore  # Specifies intentionally untracked files to ignore in Git projects; usually located in the root of a Git repository as .gitignore
  - .inputrc  # Configuration file for readline, which provides customizable input handling for many command-line tools; typically found at ~/.inputrc
  - .osx  # Custom script to configure macOS settings, not a standard file but used for personal scripts; generally placed in the home directory as ~/.osx
  - .vimrc  # Configuration file for Vim, used to set up the environment or define custom behaviors; usually located at ~/.vimrc

homebrew_installed_packages:
  # List of Homebrew packages installed on this machine
  - autoconf  # Tool for generating build configurations
  - bash-completion  # Enhances Bash shell completion capabilities
# - doxygen  # Documentation generator for software projects
# - gettext  # Set of tools for internationalization and localization (i18n/l10n)
  - gifsicle  # Command-line tool for manipulating GIF images
  - git  # Version control system from GitHub
# - gh  # GitHub CLI, a command-line interface for GitHub
  - go  # Go programming language compiler and runtime environment
  - gpg  # GNU Privacy Guard, a free replacement for PGP
  - httpie  # Modern, intuitive command-line HTTP client
  - iperf  # Tool for measuring network bandwidth and performance
  - libevent  # Event-driven I/O library for building scalable network applications
  - sqlite  # Self-contained, file-based relational database
  - nmap  # Network scanning and exploration tool
  - node  # Node.js JavaScript runtime environment
  - nvm  # Node Version Manager, which allows you to easily manage multiple versions of Node.js on your system
  - php  # PHP programming language compiler and interpreter
  - ssh-copy-id  # Tool for securely copying SSH public keys between systems
# - cowsay  # Playful command-line tool that prints ASCII art cows with customizable text
  - readline  # Library for reading input from the user, providing features like tab completion
  - openssl  # OpenSSL cryptographic toolkit (used for encryption, decryption, and more)
  - pv  # Pipe Viewer, a tool for monitoring data transfer rates and progress
  - wget  # GNU Wget command-line web downloader
  - wrk  # Modern, feature-rich HTTP benchmarking tool
  - zsh-history-substring-search  # Enhancement to the Z shell (Zsh) that allows for faster searching of command history

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
### Apps
  - google-chrome  # Fast, widely used web browser from Google
  - duckduckgo
  - firefox  # Open-source web browser known for its flexibility and privacy features
  - notion
  - jupyterlab
  - figma
# - slack  # Collaboration hub that connects your work with your team members

### AI
  - lm-studio
  - ollama
  
### Comm
  - whatsapp
  - messenger
  
### Dev
  - anaconda  # Distribution of the Python and R programming languages for scientific computing
  - pytorch  # Tensors and dynamic neural networks
  - docker  # Platform for developing, shipping, and running applications in containers
  - visual-studio  # Integrated development environment (IDE) from Microsoft for various programming languages

### Util
  - duplicate-file-finder
  - transmit  # File transfer client supporting FTP, SFTP, WebDAV, and more
  - grammarly-desktop
  - chromedriver  # WebDriver for Chrome, enabling automated control of the browser
  - sequel-ace  # Database management application for working with MySQL & MariaDB databases
#  - dropbox  # Cloud storage service for file sharing and personal backup
#  - handbrake  # Tool for converting video from nearly any format to a selection of modern codecs
#  - licecap  # Simple, animated screen capture tool that records to GIF
#  - sublime-text  # Sophisticated text editor for code, markup, and prose

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
#   - id: 967805235
#   name: "Paste - Endless Clipboard" # Clipboard history manager
# mas_email: "{{ mas_email }}"
# mas_password: "{{ mas_password }}"

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
  - name: langchain
  - name: langsmith
  - name: langchainhub
  # - name:
  #   - langchain-openai
  #   - tiktoken
  #   - pandas
  #   - duckduckgo-search
  #   state: latest
  # - name:
  #     - langchain-openai
  #     - tiktoken
  #     - pandas
  #     - duckduckgo-search
  #   state: latest
  
  # Set to 'true' to configure Sublime Text.
  # configure_sublime: false
  # sublime_base_path: '~/Library/Application Support/Sublime Text'
  # sublime_config_path: "Packages/User"
  # sublime_package_control:
  #   - "DocBlockr"
  #   - "Dockerfile Syntax Highlighting"
  #   - "FileDiffs"
  #   - "GitHub Flavored Markdown Preview"
  #   - "Jinja2"
  #   - "Package Control"
  #   - "PHP-Twig"
  #   - "Pretty JSON"
  #   - "SublimeLinter"
  #   - "SublimeLinter-contrib-yamllint"
  #   - "TrailingSpaces"
  #   - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

# Unsupported items for installation
# - Download and install HyperSwitch Window Switcher for Mac OS [https://bahoom.com/hyperswitch]
